(function () {
    'use strict';
    window.CardDesigns = window.CardDesigns || {};
    window.CardDesigns[2] = function ({ c, ui, esc, state }) {
        const tabs = [{ id: 'overview', label: '常用行動' }, { id: 'skills', label: '能力檢定' }, { id: 'gear', label: '裝備' }, { id: 'notes', label: '筆記' }];
        const pane = state.tab === 'skills' ? `${ui.attrs()}<div class="tac-list-title">技能檢定 <span>CLICK TO ROLL</span></div>${ui.skills()}` : state.tab === 'gear' ? ui.inventory() : state.tab === 'notes' ? ui.notes() : `<div class="tac-action-caption"><span>選擇行動</span><span>命中 / 效果</span></div>${ui.actions()}<div class="tac-list-title">快速檢定 <span>SKILL CHECKS</span></div>${ui.skills()}`;
        return `<div class="tactical"><aside class="tac-rail"><a href="/card" aria-label="原版角色卡">${ui.icon('dice')}</a><span>PLAYER<br>OPERATIONS</span><div class="tac-rail-line"></div><b>02</b><span>DESIGN<br>STUDY</span></aside><div class="tac-workspace">
            <header class="tac-header"><div><span class="tac-kicker"><i></i> READY FOR ADVENTURE</span><h1>輪到你了<span>。</span></h1></div><div class="tac-session"><span>LOCAL PLAYTEST</span><strong>${esc(c.system)}</strong><small>範例角色 · 本機試擲</small></div></header>
            <div class="tac-identity"><div class="tac-avatar">${ui.portrait()}</div><div class="tac-name"><h2>${esc(c.name)}</h2><span>${esc(c.role)}${c.level ? ' · LV ' + c.level : ''}</span></div><div class="tac-condition"><i></i>${esc(c.conditions[0] || '準備就緒')}</div>${ui.editButton()}</div>
            <div class="tac-status-band"><div class="tac-resource-region">${ui.resources()}</div><div class="tac-number"><span>${ui.icon('shield')} ${c.id === 'ranger' ? '護甲等級' : '護甲'}</span><strong>${esc(c.ac)}</strong><small>DEFENSE</small></div><button type="button" class="tac-number tac-initiative" data-roll="${esc(c.id === 'ranger' ? '1d20' + c.initiative : 'cc:' + c.initiative)}" data-roll-name="先攻檢定"><span>${ui.icon('dice')} 先攻</span><strong>${esc(c.initiative)}</strong><small>ROLL INITIATIVE ↗</small></button><div class="tac-number"><span>${ui.icon('compass')} 移動</span><strong>${esc(c.speed)}<small>${c.id === 'ranger' ? 'ft' : ''}</small></strong><small>MOVEMENT</small></div></div>
            <div class="tac-columns"><section class="tac-command">${ui.tabs(tabs)}<div class="tac-mode-bar"><span>${c.id === 'ranger' ? 'D20 擲骰模式' : '百分骰檢定'}</span>${c.id === 'ranger' ? `<div class="tac-mode-options" role="group" aria-label="D20 擲骰模式">${[['normal', '正常'], ['advantage', '優勢'], ['disadvantage', '劣勢']].map(([key, label]) => `<button type="button" data-advantage="${key}" aria-pressed="${state.advantage === key}">${label}</button>`).join('')}</div>` : '<small>自動顯示成功等級</small>'}</div>${pane}</section>
            <aside class="tac-feed"><div class="tac-round"><span>YOUR TURN</span><div><strong>${String(state.round).padStart(2, '0')}</strong><span>回合</span></div><button type="button" data-action="next-turn">下一回合 ${ui.icon('arrow')}</button></div><div class="tac-list-title">擲骰紀錄 <span>LIVE FEED</span></div>${ui.rollLog()}<div class="tac-feed-note">所有擲骰只在此頁面進行。<br>點擊行動或技能，立即查看結果。</div></aside></div>
            <footer class="tac-bottom"><div><span class="tac-kicker">FIELD OPERATIONS</span><span>${esc(c.location)}</span></div><div class="tac-bottom-actions"><button type="button" class="sheet-button" data-action="undo">${ui.icon('undo')} 復原</button><button type="button" class="sheet-button" data-action="rest">${ui.icon('moon')} 休息回滿</button><button type="button" class="sheet-button tac-inspiration ${c.inspiration ? 'is-on' : ''}" data-action="toggle-inspiration" aria-pressed="${c.inspiration}">${ui.icon('star')} 激勵${c.inspiration ? '已啟用' : ''}</button></div></footer>
        </div></div>`;
    };
}());
