name: ESLint

on:
  push:
    branches: [ main, master, eslint ]
  pull_request:
    branches: [ main, master, eslint ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run ESLint
      run: yarn lint

    - name: Run ESLint with output
      if: failure()
      run: |
        echo "ESLint failed. Here are the detailed results:"
        yarn lint --format=compact || true 